spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/galactic_war
    username: galactic_war
    password: galactic_war
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    gr.ioanniszisis.helldivers: DEBUG